version: '3.7'
services:
  react:
    container_name: react-draggable
    image: nginx
    build: .
    ports:
      - '8082:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf #挂载nginx配置
      - ./dist/:/usr/share/nginx/html/ #挂载项目
    restart: on-failure
